pom.xml
=> SONARWEB-57 drop Organization URL

.cix.yml, its/plugin/pom.xml, its/plugin/src/test/java/com/sonar/it/web/FileSuffixesTest.java, its/plugin/src/test/java/com/sonar/it/web/StandardMeasuresTest.java, its/plugin/src/test/java/com/sonar/it/web/VariousTest.java, its/ruling/pom.xml, its/ruling/src/test/java/org/sonar/web/it/WebRulingTest.java, pom.xml
By upgrading to orchestrator 3.19
=> Fix compatibility of integration tests with SQ 7.2

sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/AvoidCommentedOutCodeCheck.html, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/AvoidCommentedOutCodeCheck.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/AvoidHtmlCommentCheck.html, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/AvoidHtmlCommentCheck.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/ImgWithoutAltCheck.html, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S1135.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S5254.html, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/Sonar_way_profile.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/TableHeaderHasIdOrScopeCheck.html, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/TableHeaderHasIdOrScopeCheck.json, sonarpedia.json
Signed-off-by: Tibor Blenessy <tibor.blenessy@sonarsource.com>
=> Update rule metadata

sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/sonar/DeprecatedAttributesInHtml5Check.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/node/TagNode.java, sonar-html-plugin/src/test/java/org/sonar/plugins/html/checks/sonar/DeprecatedAttributesInHtml5CheckTest.java, sonar-html-plugin/src/test/java/org/sonar/plugins/html/node/TagNodeTest.java, sonar-html-plugin/src/test/resources/checks/deprecatedAttributesInHtml5.html
Duplicates #146 to trigger all tests.
=> SONARHTML-118 Support angular [attr.*] binding

sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/HtmlIssue.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/security/package-info.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/sonar/DeprecatedAttributesInHtml5Check.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/lex/AbstractTokenizer.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/node/Node.java
reduce visibility of abstract class constructor
add missing package.info
add missing locale
add missing Nullable
=> Fix quality flaw:

sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/comments/AvoidHtmlCommentCheck.java, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/AvoidHtmlCommentCheck.html, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/AvoidHtmlCommentCheck.json, sonar-html-plugin/src/test/java/org/sonar/plugins/html/checks/comments/AvoidHtmlCommentCheckTest.java
=> SONARHTML-124 Rule S1876 (AvoidHtmlCommentCheck): change rule type to Security Hotspot

.cirrus.yml, .github/workflows/release.yml
=> BUILD-2184 Use Vault

sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/sonar/VideoTrackCheck.java, sonar-html-plugin/src/test/java/org/sonar/plugins/html/checks/sonar/VideoTrackCheckTest.java, sonar-html-plugin/src/test/resources/checks/VideoTrackCheck.html
=> SONARHTML-174 Fix NPE in S4084 VideoTrackCheck

sonar-html-plugin/src/main/java/org/sonar/plugins/html/api/HtmlConstants.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/api/accessibility/package-info.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/accessibility/FocusableInteractiveElementsCheck.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/accessibility/NoAriaHiddenOnFocusableCheck.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/accessibility/NoNonInteractiveElementsWithHandlersCheck.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/accessibility/NoStaticElementInteractionsCheck.java
Fix multiple issues that appeared after merging to `master`
=> Fix issues

sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/coding/FileLengthCheck.java
Noticed that there was some overkill included in this rule. Let us simplify.
=> Simplify file line check

sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/accessibility/RoleSupportsAriaPropertyCheck.java, sonar-html-plugin/src/test/java/org/sonar/plugins/html/checks/accessibility/RoleSupportsAriaPropertyCheckTest.java, sonar-html-plugin/src/test/resources/checks/RoleSupportsAriaPropertyCheck.html
Fixes https://sonarsource.atlassian.net/browse/SONARHTML-228
=> SONARHTML-228 - Fix S6811: Support multiple roles

sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/accessibility/ElementWithRoleShouldHaveRequiredPropertiesCheck.java, sonar-html-plugin/src/test/java/org/sonar/plugins/html/checks/accessibility/ElementWithRoleShouldHaveRequiredPropertiesCheckTest.java, sonar-html-plugin/src/test/resources/checks/ElementWithRoleShouldHaveRequiredPropertiesCheckTest/invalid.html, sonar-html-plugin/src/test/resources/checks/ElementWithRoleShouldHaveRequiredPropertiesCheckTest/valid.html
Fixes https://sonarsource.atlassian.net/browse/SONARHTML-229
=> SONARHTML-229 - Fix S6807: Support multiple roles

sonar-html-plugin/src/main/java/org/sonar/plugins/html/api/Helpers.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/accessibility/AriaProptypesCheck.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/accessibility/AriaRoleCheck.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/accessibility/ElementWithRoleShouldHaveRequiredPropertiesCheck.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/accessibility/FocusableInteractiveElementsCheck.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/accessibility/NoRedundantRolesCheck.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/sonar/MouseEventWithoutKeyboardEquivalentCheck.java, sonar-html-plugin/src/test/resources/checks/AriaRoleCheck.html
Checked in peach and found a few issues with PHP inputting dynamic roles: https://peach.aws-prd.sonarsource.com/issues?projects=php%3Amagento2&resolved=false&rules=Web%3AS6821&open=AY7MwfK6A7MosuAUJtRS
=> SONARHTML-214  Handle dynamic values for S6821

.github/workflows/releasability.yml
[SONARHTML-275](https://sonarsource.atlassian.net/browse/SONARHTML-275)
[SONARHTML-275]: https://sonarsource.atlassian.net/browse/SONARHTML-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARHTML-275 Add releasability check

sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/ParentElementIllegalCheck.html, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S1135.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6807.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6811.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6819.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6822.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6823.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6824.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6844.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6845.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6846.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6847.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6848.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6851.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6852.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6853.json, sonarpedia.json
[SONARHTML-294](https://sonarsource.atlassian.net/browse/SONARHTML-294)
[SONARHTML-294]: https://sonarsource.atlassian.net/browse/SONARHTML-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARHTML-294 Fix discrepancies between MQR and severity for HTML rules

.github/workflows/PullRequestClosed.yml
[SONARHTML-296](https://sonarsource.atlassian.net/browse/SONARHTML-296)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SONARHTML-296]: https://sonarsource.atlassian.net/browse/SONARHTML-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARHTML-296 Autoclose issues created by Jira integration

sonar-html-plugin/src/main/java/org/sonar/plugins/html/api/accessibility/ControlGroup.java
[SONARHTML-283](https://sonarsource.atlassian.net/browse/SONARHTML-283)
[SONARHTML-283]: https://sonarsource.atlassian.net/browse/SONARHTML-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARHTML-283 S6840 triggers on custom components

.cirrus.yml, .cirrus/run-iris.sh, .gitignore, coverage-report/pom.xml, pom.xml
[SONARHTML-303](https://sonarsource.atlassian.net/browse/SONARHTML-303)
[SONARHTML-303]: https://sonarsource.atlassian.net/browse/SONARHTML-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARHTML-303 Unify Platform Dogfooding

pom.xml
[SONARHTML-306](https://sonarsource.atlassian.net/browse/SONARHTML-306)
[SONARHTML-306]: https://sonarsource.atlassian.net/browse/SONARHTML-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARHTML-306 Fix coverage

.github/renovate.json, .github/workflows/release.yml, pom.xml
[SONARHTML-308](https://sonarsource.atlassian.net/browse/SONARHTML-308)
update slack channel
[SONARHTML-308]: https://sonarsource.atlassian.net/browse/SONARHTML-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARHTML-308 Renovate: Ignore its

sonar-html-plugin/src/main/java/org/sonar/plugins/html/HtmlPlugin.java
[SONARHTML-311](https://sonarsource.atlassian.net/browse/SONARHTML-311)
[SONARHTML-311]: https://sonarsource.atlassian.net/browse/SONARHTML-311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARHTML-311 Fix HtmlPlugin.java deprecation

coverage-report/pom.xml, its/ruling/src/test/resources/expected/Web-S7926.json, sonar-html-plugin/src/main/java/org/sonar/plugins/html/checks/accessibility/MetaAllowZoomCheck.java, sonar-html-plugin/src/main/java/org/sonar/plugins/html/rules/CheckClasses.java, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/FileLengthCheck.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/ParentElementIllegalCheck.html, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S6793.html, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S7926.html, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/S7926.json, sonar-html-plugin/src/main/resources/org/sonar/l10n/web/rules/Web/Sonar_way_profile.json, sonar-html-plugin/src/test/java/org/sonar/plugins/html/checks/accessibility/MetaAllowZoomCheckTest.java, sonar-html-plugin/src/test/resources/checks/MetaAllowZoomCheck.html, sonarpedia.json
[SONARHTML-314](https://sonarsource.atlassian.net/browse/SONARHTML-314)
[SONARHTML-314]: https://sonarsource.atlassian.net/browse/SONARHTML-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONARHTML-314 Add implementation for rule S7926: Meta viewport allow zoom
